version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: idf-task-clickhouse-1
    ports:
      - "8123:8123"   
      - "9000:9000"   
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=idftask
      - CLICKHOUSE_PASSWORD=idftask
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./scripts:/scripts

volumes:
  clickhouse_data:
